# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'YourMentor' do
  use_frameworks!

  # Pods for YourMentor
  pod 'Alamofire', '~> 5.10.2'
  pod 'KakaoSDK'
  pod 'RxSwift'
  pod 'RxCocoa'

  post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
  end
end

end
